[package]
name = "day2"
version = "0.1.0"
edition = "2021"
authors = ["Cole Trammer <cole.trammer@gmail.com>"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
